// MAIN
GET http://localhost:3001/

###
// GET INFO
GET http://localhost:3001/info

###

// GET THEM ALL
GET http://localhost:3001/api/p

###

// GET SPECIFIC PERSON
GET http://localhost:3001/api/persons/65904723a66300f186ed65fb

###

// DELETE PERSON
DELETE http://localhost:3001/api/persons/65904723a66300f186ed65fb

###

// ADD PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Tortilla",
  "number": "123456"
}


